// Generated by scripts/gen/gen_cave_vocab.py from the caves sidecar (scripts/gen/extract_caves.lua). Do not edit.
export const CAVE_REQUIRED_TASK_IDS: readonly string[] = ["MudWorld", "MudCave", "MudLights", "MudPit", "BigBatCave", "RockyLand", "RedForest", "GreenForest", "BlueForest", "SpillagmiteCaverns", "MoonCaveForest", "ArchiveMaze", "CaveExitTask1", "CaveExitTask2", "CaveExitTask3", "CaveExitTask4", "CaveExitTask5", "CaveExitTask6", "CaveExitTask7", "CaveExitTask8", "CaveExitTask9", "CaveExitTask10", "CentipedeCaveTask", "ToadStoolTask1", "ToadStoolTask2", "ToadStoolTask3", "LichenLand", "Residential", "Military", "Sacred", "TheLabyrinth", "SacredAltar", "AtriumMaze"];
export const CAVE_OPTIONAL_TASK_IDS: readonly string[] = ["SwampySinkhole", "CaveSwamp", "UndergroundForest", "PleasantSinkhole", "FungalNoiseForest", "FungalNoiseMeadow", "BatCloister", "RabbitTown", "RabbitCity", "SpiderLand", "RabbitSpiderWar", "MoreAltars", "CaveJungle", "SacredDanger", "MilitaryPits", "MuddySacred", "Residential2", "Residential3"];
export const CAVE_OPTIONAL_PICKED = 8;

export type CavePieceKind = "boon" | "trap" | "poi" | "protected" | "fixed";

export interface CavePieceVocab {
    id: string;
    kind: CavePieceKind;
    rare: boolean;
    maxCount: number;
    fixedCount?: number;
    candidateTasks?: readonly string[];
}

export const CAVE_PIECES: readonly CavePieceVocab[] = [
    { id: "ResurrectionStone", kind: "fixed", rare: false, maxCount: 2, fixedCount: 2, candidateTasks: ["MudWorld", "MudCave", "MudLights", "MudPit", "BigBatCave", "RockyLand", "RedForest", "GreenForest", "BlueForest", "SpillagmiteCaverns", "SwampySinkhole", "CaveSwamp", "UndergroundForest", "PleasantSinkhole", "FungalNoiseForest", "FungalNoiseMeadow", "BatCloister", "RabbitTown", "RabbitCity", "SpiderLand", "RabbitSpiderWar", "CentipedeCaveTask"] },
    { id: "TentaclePillar", kind: "fixed", rare: false, maxCount: 10, fixedCount: 10, candidateTasks: ["MudWorld", "MudCave", "MudLights", "MudPit", "BigBatCave", "RockyLand", "RedForest", "GreenForest", "BlueForest", "SpillagmiteCaverns", "SwampySinkhole", "CaveSwamp", "UndergroundForest", "PleasantSinkhole", "FungalNoiseForest", "FungalNoiseMeadow", "BatCloister", "RabbitTown", "RabbitCity", "SpiderLand", "RabbitSpiderWar", "CentipedeCaveTask"] },
    { id: "skeleton_notplayer", kind: "fixed", rare: false, maxCount: 1, fixedCount: 1, candidateTasks: ["MudWorld", "MudCave", "MudLights", "MudPit", "BigBatCave", "RockyLand", "RedForest", "GreenForest", "BlueForest", "SpillagmiteCaverns", "SwampySinkhole", "CaveSwamp", "UndergroundForest", "PleasantSinkhole", "FungalNoiseForest", "FungalNoiseMeadow", "BatCloister", "RabbitTown", "RabbitCity", "SpiderLand", "RabbitSpiderWar", "CentipedeCaveTask"] },
    { id: "TentaclePillarToAtrium", kind: "fixed", rare: false, maxCount: 1, fixedCount: 1, candidateTasks: ["BigBatCave", "GreenForest", "CentipedeCaveTask"] },
    { id: "Fire Hounds", kind: "trap", rare: false, maxCount: 1 },
    { id: "Ice Hounds", kind: "trap", rare: false, maxCount: 1 },
    { id: "Dev Graveyard", kind: "trap", rare: true, maxCount: 1 },
    { id: "skeleton_mushjack", kind: "poi", rare: false, maxCount: 1, candidateTasks: ["RedForest", "GreenForest", "BlueForest", "FungalNoiseForest", "FungalNoiseMeadow"] },
    { id: "skeleton_researchlab1", kind: "poi", rare: true, maxCount: 1 },
    { id: "skeleton_researchlab3", kind: "poi", rare: true, maxCount: 1 },
    { id: "skeleton_researchlab2", kind: "poi", rare: true, maxCount: 1 },
    { id: "skeleton_dapper", kind: "poi", rare: true, maxCount: 1 },
    { id: "skeleton_lightfarmer", kind: "poi", rare: false, maxCount: 1, candidateTasks: ["MudWorld", "MudCave", "MudLights", "MudPit", "ToadStoolTask1", "ToadStoolTask3", "LichenLand", "CaveJungle"] },
    { id: "skeleton_lumberjack", kind: "poi", rare: false, maxCount: 1, candidateTasks: ["CaveExitTask1", "CaveExitTask2", "CaveExitTask3", "CaveExitTask4", "CaveExitTask5", "CaveExitTask6", "CaveExitTask7", "CaveExitTask8", "CaveExitTask9", "CaveExitTask10", "UndergroundForest", "PleasantSinkhole", "RabbitTown", "RabbitCity", "SpiderLand", "RabbitSpiderWar"] },
    { id: "skeleton_farmer", kind: "poi", rare: false, maxCount: 1, candidateTasks: ["CaveExitTask1", "CaveExitTask2", "CaveExitTask3", "CaveExitTask4", "CaveExitTask5", "CaveExitTask6", "CaveExitTask7", "CaveExitTask8", "CaveExitTask9", "CaveExitTask10", "UndergroundForest", "PleasantSinkhole", "RabbitTown", "RabbitCity", "SpiderLand", "RabbitSpiderWar"] },
    { id: "skeleton_entomologist", kind: "poi", rare: false, maxCount: 1, candidateTasks: ["CaveExitTask1", "CaveExitTask2", "CaveExitTask3", "CaveExitTask4", "CaveExitTask5", "CaveExitTask6", "CaveExitTask7", "CaveExitTask8", "CaveExitTask9", "CaveExitTask10", "UndergroundForest", "PleasantSinkhole", "RabbitTown", "RabbitCity", "SpiderLand", "RabbitSpiderWar"] },
    { id: "skeleton_miner", kind: "poi", rare: false, maxCount: 1, candidateTasks: ["BigBatCave", "RockyLand", "ToadStoolTask2", "BatCloister", "SpillagmiteCaverns"] },
    { id: "skeleton_batfight", kind: "poi", rare: false, maxCount: 1, candidateTasks: ["BigBatCave", "RockyLand", "ToadStoolTask2", "BatCloister"] },
    { id: "skeleton_warrior", kind: "poi", rare: false, maxCount: 1 },
    { id: "skeleton_wizard_ice", kind: "poi", rare: false, maxCount: 1 },
    { id: "skeleton_wizard_fire", kind: "poi", rare: false, maxCount: 1 },
    { id: "skeleton_rain_coat", kind: "poi", rare: false, maxCount: 1 },
    { id: "skeleton_fisher", kind: "poi", rare: false, maxCount: 1 },
    { id: "skeleton_graverobber", kind: "poi", rare: false, maxCount: 1 },
    { id: "skeleton_night_hunter", kind: "poi", rare: false, maxCount: 1 },
    { id: "skeleton_construction", kind: "poi", rare: false, maxCount: 1 },
    { id: "skeleton_summer", kind: "poi", rare: false, maxCount: 1 },
    { id: "lures_and_worms", kind: "protected", rare: false, maxCount: 1, candidateTasks: ["MudWorld", "MudCave", "MudLights", "MudPit", "ToadStoolTask1", "ToadStoolTask3", "LichenLand", "CaveJungle"] },
    { id: "FishingBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "CookingBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "Level2GrassBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "MiscBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "Level2TwigsBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "Level2WoodBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "GrassBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "FarmingBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "WeaponBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "WoodBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "Level2RockBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "RockBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "TwigsBoon", kind: "boon", rare: false, maxCount: 8 },
    { id: "Level4Boon", kind: "boon", rare: true, maxCount: 8 }
];

export const CAVE_SWAPS: readonly { category: string; options: readonly string[] }[] = [
    { category: "grass", options: ["regular grass"] },
    { category: "twigs", options: ["regular twigs", "twiggy trees"] },
    { category: "berries", options: ["regular berries", "juicy berries"] }
];
