// Generated by scripts/gen/gen_website_catalog.mjs from scripts/catalog/catalog.json. Do not edit.
export const GAME_BUILD = 747465;
export const SAMPLE_WORLDS = 313;

export const PREFAB_GROUP_IDS = ["spawn & travel", "bosses & spawners", "landmarks", "clockwork", "sculptures", "statues", "trees", "rocks", "plants", "mobs & dens", "structures", "items", "set-piece loot", "ocean", "markers"] as const;
export type PrefabGroupId = (typeof PREFAB_GROUP_IDS)[number];

export interface WorldPrefab {
    id: string;
    name: string;
    group: PrefabGroupId;
    variantOf?: string;
    unreachable?: true;
    always?: true;
    unique?: true;
    counts?: [min: number, median: number, max: number];
    swapOption?: string;
}

export interface PrefabGroup {
    id: PrefabGroupId;
    name: string;
    prefabs: string[];
}

export interface LandTile {
    name: string;
    displayName: string;
    inDefaultWorlds?: true;
}

export interface MapTile {
    displayName: string;
    kind: "land" | "ocean" | "impassable" | "invalid";
    color: [r: number, g: number, b: number];
}

export interface NamedAnchor {
    id: string;
    label: string;
}

export const PREFABS: WorldPrefab[] = [
    { "id": "amulet", "name": "Life Giving Amulet", "group": "set-piece loot", "unique": true },
    {
        "id": "antlion_spawner",
        "name": "Antlion",
        "group": "bosses & spawners",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "armorgrass", "name": "Grass Suit", "group": "set-piece loot", "counts": [0, 0, 2] },
    { "id": "armormarble", "name": "Marble Suit", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "armorwood", "name": "Log Suit", "group": "set-piece loot", "counts": [0, 0, 3] },
    { "id": "ash", "name": "Ashes", "group": "set-piece loot", "counts": [0, 0, 8] },
    { "id": "axe", "name": "Axe", "group": "set-piece loot", "counts": [0, 1, 3] },
    { "id": "backpack", "name": "Backpack", "group": "set-piece loot", "counts": [0, 0, 2] },
    {
        "id": "balatro_machine",
        "name": "JIMBO",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "bananabush", "name": "Banana Bush", "group": "plants", "always": true, "counts": [4, 5, 9] },
    { "id": "bandage", "name": "Honey Poultice", "group": "set-piece loot", "counts": [0, 0, 2] },
    { "id": "basalt", "name": "Basalt", "group": "rocks", "counts": [0, 0, 20] },
    { "id": "bat", "name": "Batilisk", "group": "mobs & dens", "unreachable": true, "unique": true },
    { "id": "batbat", "name": "Bat Bat", "group": "set-piece loot", "unreachable": true, "unique": true },
    {
        "id": "bathbomb",
        "name": "Bath Bomb",
        "group": "set-piece loot",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "batwing", "name": "Batilisk Wing", "group": "set-piece loot", "unreachable": true, "unique": true },
    { "id": "beardhair", "name": "Beard Hair", "group": "set-piece loot", "counts": [0, 0, 5] },
    { "id": "bedroll_straw", "name": "Straw Roll", "group": "set-piece loot", "always": true, "counts": [1, 1, 2] },
    { "id": "beebox", "name": "Bee Box", "group": "structures", "unique": true },
    {
        "id": "beebox_hermit",
        "name": "Bee Box (Crabby Hermit)",
        "group": "structures",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "beefalo", "name": "Beefalo", "group": "mobs & dens", "always": true, "counts": [3, 20, 67] },
    { "id": "beefalohat", "name": "Beefalo Hat", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "beefalowool", "name": "Beefalo Wool", "group": "set-piece loot", "counts": [0, 0, 7] },
    { "id": "beehat", "name": "Beekeeper Hat", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "beehive", "name": "Beehive", "group": "mobs & dens", "always": true, "counts": [4, 41, 132] },
    { "id": "beemine", "name": "Bee Mine", "group": "set-piece loot", "counts": [0, 0, 2] },
    {
        "id": "beequeenhive",
        "name": "Bee Queen (Gigantic Beehive)",
        "group": "bosses & spawners",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "beeswax", "name": "Beeswax", "group": "set-piece loot", "unreachable": true, "unique": true },
    {
        "id": "berrybush",
        "name": "Berry Bush (regular)",
        "group": "plants",
        "variantOf": "berrybush",
        "counts": [0, 137, 266],
        "swapOption": "regular berries"
    },
    {
        "id": "berrybush2",
        "name": "Berry Bush (variant 2)",
        "group": "plants",
        "variantOf": "berrybush",
        "counts": [0, 6, 39]
    },
    {
        "id": "berrybush_juicy",
        "name": "Juicy Berry Bush",
        "group": "plants",
        "variantOf": "berrybush",
        "counts": [0, 0, 123],
        "swapOption": "juicy berries"
    },
    { "id": "birdtrap", "name": "Bird Trap", "group": "structures", "counts": [0, 0, 2] },
    { "id": "bishop", "name": "Clockwork Bishop", "group": "clockwork", "counts": [0, 0, 4] },
    { "id": "blowdart_fire", "name": "Fire Dart", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "blowdart_pipe", "name": "Blow Dart", "group": "set-piece loot", "counts": [0, 0, 2] },
    { "id": "blowdart_sleep", "name": "Sleep Dart", "group": "set-piece loot", "counts": [0, 0, 2] },
    { "id": "blue_mushroom", "name": "Blue Mushroom", "group": "plants", "always": true, "counts": [7, 34, 79] },
    { "id": "bluegem", "name": "Blue Gem", "group": "set-piece loot", "unique": true },
    { "id": "blueprint", "name": "Blueprint", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "boards", "name": "Boards", "group": "set-piece loot", "counts": [0, 2, 15] },
    { "id": "boat", "name": "Boat", "group": "ocean", "counts": [0, 1, 2] },
    { "id": "boat_cannon", "name": "Cannon", "group": "ocean", "counts": [0, 2, 7] },
    { "id": "boat_otterden", "name": "Marotter Raft", "group": "mobs & dens", "always": true, "counts": [14, 31, 51] },
    { "id": "boat_pirate", "name": "Pirate Sloop", "group": "ocean", "always": true, "counts": [3, 3, 3] },
    {
        "id": "boatfragment03",
        "name": "Boat Fragment (3)",
        "group": "ocean",
        "variantOf": "boatfragment",
        "always": true,
        "counts": [2, 11, 44]
    },
    {
        "id": "boatfragment04",
        "name": "Boat Fragment (4)",
        "group": "ocean",
        "variantOf": "boatfragment",
        "always": true,
        "counts": [1, 11, 44]
    },
    {
        "id": "boatfragment05",
        "name": "Boat Fragment (5)",
        "group": "ocean",
        "variantOf": "boatfragment",
        "counts": [0, 11, 44]
    },
    { "id": "boomerang", "name": "Boomerang", "group": "set-piece loot", "counts": [0, 0, 2] },
    { "id": "bugnet", "name": "Bug Net", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    {
        "id": "bullkelp_beachedroot",
        "name": "Beached Bull Kelp Stalk",
        "group": "plants",
        "always": true,
        "counts": [27, 49, 84]
    },
    { "id": "bullkelp_plant", "name": "Bull Kelp", "group": "plants", "always": true, "counts": [191, 260, 315] },
    { "id": "burnt_marsh_bush", "name": "Spiky Bush (burnt)", "group": "plants", "always": true, "counts": [5, 6, 6] },
    {
        "id": "burntground_faded",
        "name": "Scorched ground (faded)",
        "group": "markers",
        "always": true,
        "counts": [6, 15, 32]
    },
    { "id": "bushhat", "name": "Bush Hat", "group": "set-piece loot", "counts": [0, 0, 2] },
    {
        "id": "buzzardspawner",
        "name": "Buzzards (circling)",
        "group": "mobs & dens",
        "always": true,
        "counts": [3, 14, 41]
    },
    { "id": "cactus", "name": "Cactus", "group": "plants", "always": true, "counts": [7, 27, 55] },
    { "id": "cane", "name": "Walking Cane", "group": "set-piece loot", "counts": [0, 0, 2] },
    {
        "id": "carrat_planted",
        "name": "Carrot (Carrat)",
        "group": "mobs & dens",
        "always": true,
        "counts": [8, 25, 47]
    },
    { "id": "carrot_planted", "name": "Carrot", "group": "plants", "always": true, "counts": [52, 103, 191] },
    { "id": "catcoonden", "name": "Hollow Stump", "group": "mobs & dens", "always": true, "counts": [1, 7, 20] },
    {
        "id": "cave_entrance",
        "name": "Plugged Sinkhole",
        "group": "spawn & travel",
        "always": true,
        "counts": [8, 10, 10]
    },
    {
        "id": "charlie_stage_post",
        "name": "Stage",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "chester_eyebone",
        "name": "Eye Bone",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "chum", "name": "Fish Food", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "cookbook", "name": "Cookbook", "group": "set-piece loot", "counts": [0, 0, 3] },
    {
        "id": "cookiecutter_spawner",
        "name": "Cookie Cutters (spawner)",
        "group": "mobs & dens",
        "always": true,
        "counts": [28, 28, 28]
    },
    { "id": "cookingrecipecard", "name": "{item} Recipe Card", "group": "set-piece loot", "counts": [0, 0, 6] },
    { "id": "cookpot", "name": "Crock Pot", "group": "structures", "counts": [0, 0, 3] },
    {
        "id": "crabking_spawner",
        "name": "Crab King",
        "group": "bosses & spawners",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "critterlab",
        "name": "Rock Den",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "cutgrass", "name": "Cut Grass", "group": "items", "counts": [0, 3, 16] },
    { "id": "cutstone", "name": "Cut Stone", "group": "set-piece loot", "counts": [0, 0, 10] },
    { "id": "dead_sea_bones", "name": "Sea Bones", "group": "ocean", "always": true, "counts": [5, 23, 48] },
    { "id": "deciduoustree", "name": "Birchnut Tree", "group": "trees", "always": true, "counts": [319, 773, 1561] },
    {
        "id": "deciduoustree_stump",
        "name": "Birchnut Tree (stump)",
        "group": "trees",
        "variantOf": "deciduoustree",
        "always": true,
        "counts": [2, 2, 2]
    },
    {
        "id": "deerspawningground",
        "name": "Klaus / No-Eyed Deer spawning ground",
        "group": "bosses & spawners",
        "always": true,
        "counts": [11, 25, 40]
    },
    {
        "id": "dock_tile_registrator",
        "name": "Monkey Island dock tile (marker)",
        "group": "markers",
        "always": true,
        "counts": [62, 117, 157]
    },
    { "id": "dock_woodposts", "name": "Dock Piling", "group": "structures", "always": true, "counts": [31, 63, 97] },
    {
        "id": "dragonfly_spawner",
        "name": "Dragonfly",
        "group": "bosses & spawners",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "driftwood_log",
        "name": "Driftwood Piece",
        "group": "ocean",
        "variantOf": "driftwood",
        "always": true,
        "counts": [63, 104, 146]
    },
    {
        "id": "driftwood_small1",
        "name": "Driftwood (small 1)",
        "group": "trees",
        "variantOf": "driftwood",
        "always": true,
        "counts": [6, 16, 36]
    },
    {
        "id": "driftwood_small2",
        "name": "Driftwood (small 2)",
        "group": "trees",
        "variantOf": "driftwood",
        "always": true,
        "counts": [6, 17, 38]
    },
    {
        "id": "driftwood_tall",
        "name": "Driftwood (tall)",
        "group": "trees",
        "variantOf": "driftwood",
        "always": true,
        "counts": [1, 5, 17]
    },
    {
        "id": "evergreen",
        "name": "Evergreen",
        "group": "trees",
        "variantOf": "evergreen",
        "always": true,
        "counts": [1272, 3497, 6373]
    },
    {
        "id": "evergreen_normal",
        "name": "Evergreen (normal)",
        "group": "trees",
        "variantOf": "evergreen",
        "counts": [0, 0, 5]
    },
    {
        "id": "evergreen_short",
        "name": "Evergreen (short)",
        "group": "trees",
        "variantOf": "evergreen",
        "counts": [0, 0, 33]
    },
    {
        "id": "evergreen_sparse",
        "name": "Lumpy Evergreen (lumpy)",
        "group": "trees",
        "variantOf": "evergreen_sparse",
        "always": true,
        "counts": [130, 599, 1612]
    },
    {
        "id": "evergreen_stump",
        "name": "Evergreen (stump)",
        "group": "trees",
        "variantOf": "evergreen",
        "counts": [0, 4, 10]
    },
    {
        "id": "evergreen_tall",
        "name": "Evergreen (tall)",
        "group": "trees",
        "variantOf": "evergreen",
        "counts": [0, 0, 39]
    },
    { "id": "farm_plant_pumpkin", "name": "Pumpkin Plant", "group": "plants", "unreachable": true, "unique": true },
    { "id": "farm_plow_item", "name": "Garden Digamajig", "group": "set-piece loot", "counts": [0, 0, 3] },
    { "id": "featherhat", "name": "Feather Hat", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "fertilizer", "name": "Bucket-o-poop", "group": "set-piece loot", "unreachable": true, "unique": true },
    { "id": "fireflies", "name": "Fireflies", "group": "plants", "always": true, "counts": [276, 372, 577] },
    { "id": "firehound", "name": "Fire Hound", "group": "mobs & dens", "counts": [0, 0, 5] },
    { "id": "firepit", "name": "Fire Pit", "group": "structures", "unique": true },
    { "id": "firestaff", "name": "Fire Staff", "group": "set-piece loot", "counts": [0, 0, 2] },
    {
        "id": "fishingrod",
        "name": "Freshwater Fishing Rod",
        "group": "set-piece loot",
        "always": true,
        "counts": [1, 1, 2]
    },
    { "id": "flint", "name": "Flint", "group": "items", "always": true, "counts": [83, 184, 306] },
    { "id": "flower", "name": "Flower", "group": "plants", "always": true, "counts": [249, 523, 1044] },
    { "id": "flower_cave", "name": "Light Flower", "group": "plants", "unreachable": true, "unique": true },
    {
        "id": "flower_cave_double",
        "name": "Light Flower (double)",
        "group": "plants",
        "variantOf": "flower_cave",
        "unreachable": true,
        "unique": true
    },
    {
        "id": "flower_cave_triple",
        "name": "Light Flower (triple)",
        "group": "plants",
        "variantOf": "flower_cave",
        "unreachable": true,
        "unique": true
    },
    { "id": "flower_evil", "name": "Evil Flower", "group": "plants", "counts": [0, 29, 77] },
    { "id": "flower_rose", "name": "Rose", "group": "plants", "always": true, "counts": [2, 5, 5] },
    { "id": "footballhat", "name": "Football Helmet", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "fruitdragon", "name": "Saladmander", "group": "mobs & dens", "always": true, "counts": [6, 16, 33] },
    {
        "id": "gargoyle_houndatk",
        "name": "Suspicious Moonrock (hound, attacking)",
        "group": "statues",
        "variantOf": "gargoyle",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "gargoyle_hounddeath",
        "name": "Suspicious Moonrock (hound, dying)",
        "group": "statues",
        "variantOf": "gargoyle",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "gargoyle_werepighowl",
        "name": "Suspicious Moonrock (werepig, howling)",
        "group": "statues",
        "variantOf": "gargoyle",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "gears", "name": "Gears", "group": "set-piece loot", "counts": [0, 0, 6] },
    { "id": "goldenpickaxe", "name": "Opulent Pickaxe", "group": "set-piece loot", "unique": true },
    { "id": "goldnugget", "name": "Gold Nugget", "group": "items", "always": true, "counts": [1, 9, 19] },
    {
        "id": "grass",
        "name": "Grass",
        "group": "plants",
        "always": true,
        "counts": [137, 629, 1323],
        "swapOption": "regular grass"
    },
    {
        "id": "grassgekko",
        "name": "Grass Gekko",
        "group": "plants",
        "counts": [0, 0, 203],
        "swapOption": "grass gekko"
    },
    { "id": "gravestone", "name": "Headstone", "group": "structures", "always": true, "counts": [7, 22, 48] },
    { "id": "green_mushroom", "name": "Green Mushroom", "group": "plants", "always": true, "counts": [38, 75, 155] },
    { "id": "guano", "name": "Guano", "group": "set-piece loot", "counts": [0, 0, 3] },
    { "id": "gunpowder", "name": "Gunpowder", "group": "set-piece loot", "counts": [0, 0, 2] },
    { "id": "hambat", "name": "Ham Bat", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "hammer", "name": "Hammer", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    {
        "id": "hermitcrab_lure_marker",
        "name": "Crabby Hermit lure spot (marker)",
        "group": "markers",
        "variantOf": "hermitcrab",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "hermitcrab_marker",
        "name": "Crabby Hermit island (marker)",
        "group": "markers",
        "variantOf": "hermitcrab",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "hermitcrab_marker_fishing",
        "name": "Crabby Hermit fishing spot (marker)",
        "group": "markers",
        "variantOf": "hermitcrab",
        "always": true,
        "counts": [16, 16, 16]
    },
    {
        "id": "hermithouse_construction1",
        "name": "Crabby Hermit (Pearl's ruined house)",
        "group": "bosses & spawners",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "hotspring", "name": "Hot Spring", "group": "landmarks", "always": true, "counts": [3, 9, 17] },
    { "id": "houndbone", "name": "Bones", "group": "structures", "always": true, "counts": [16, 58, 104] },
    { "id": "houndmound", "name": "Hound Mound", "group": "mobs & dens", "counts": [0, 5, 31] },
    { "id": "houndstooth", "name": "Hound's Tooth", "group": "set-piece loot", "counts": [0, 0, 4] },
    { "id": "icehound", "name": "Ice Hound", "group": "mobs & dens", "counts": [0, 0, 5] },
    { "id": "icestaff", "name": "Ice Staff", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "insanityrock", "name": "Obelisk (insane)", "group": "structures", "always": true, "counts": [4, 4, 4] },
    { "id": "junk_pile", "name": "Junk Pile", "group": "landmarks", "always": true, "counts": [9, 9, 9] },
    {
        "id": "junk_pile_big",
        "name": "Teetering Junk Pile",
        "group": "landmarks",
        "variantOf": "junk_pile",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "knight", "name": "Clockwork Knight", "group": "clockwork", "always": true, "counts": [1, 4, 14] },
    { "id": "lantern", "name": "Lantern", "group": "set-piece loot", "unreachable": true, "unique": true },
    { "id": "lava_pond", "name": "Magma", "group": "landmarks", "always": true, "counts": [6, 6, 6] },
    { "id": "leif", "name": "Treeguard", "group": "bosses & spawners", "counts": [0, 0, 14] },
    { "id": "lightcrab", "name": "Crustashine", "group": "mobs & dens", "always": true, "counts": [4, 6, 8] },
    { "id": "lightninggoat", "name": "Volt Goat", "group": "mobs & dens", "always": true, "counts": [3, 4, 6] },
    { "id": "livingtree", "name": "Totally Normal Tree", "group": "landmarks", "counts": [0, 2, 6] },
    { "id": "log", "name": "Log", "group": "items", "counts": [0, 3, 19] },
    { "id": "mandrake_planted", "name": "Mandrake", "group": "plants", "always": true, "counts": [2, 3, 4] },
    { "id": "marble", "name": "Marble", "group": "items", "counts": [0, 2, 6] },
    { "id": "marblepillar", "name": "Marble Pillar", "group": "statues", "counts": [0, 0, 8] },
    { "id": "marbletree", "name": "Marble Tree", "group": "statues", "counts": [0, 5, 26] },
    { "id": "marsh_bush", "name": "Spiky Bush (marsh)", "group": "plants", "always": true, "counts": [52, 141, 257] },
    { "id": "marsh_tree", "name": "Spiky Tree", "group": "trees", "always": true, "counts": [62, 228, 448] },
    { "id": "mast_broken", "name": "Broken Mast", "group": "ocean", "unique": true, "counts": [0, 0, 1] },
    { "id": "meatrack", "name": "Drying Rack", "group": "structures", "counts": [0, 0, 2] },
    {
        "id": "meatrack_hermit",
        "name": "Drying Rack (Crabby Hermit)",
        "group": "structures",
        "always": true,
        "counts": [6, 6, 6]
    },
    { "id": "merm", "name": "Merm", "group": "mobs & dens", "counts": [0, 1, 11] },
    { "id": "mermhead", "name": "Merm Head", "group": "structures", "counts": [0, 0, 3] },
    { "id": "mermhouse", "name": "Leaky Shack", "group": "mobs & dens", "counts": [0, 7, 22] },
    { "id": "messagebottle", "name": "Message in a Bottle", "group": "ocean", "always": true, "counts": [1, 8, 17] },
    { "id": "meteorspawner", "name": "Meteor field", "group": "markers", "always": true, "counts": [2, 6, 13] },
    { "id": "minerhat", "name": "Miner Hat", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "molehat", "name": "Moggles", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "molehill", "name": "Burrow", "group": "mobs & dens", "always": true, "counts": [6, 30, 84] },
    { "id": "monkeyhut", "name": "Monkey Hut", "group": "mobs & dens", "always": true, "counts": [4, 8, 18] },
    {
        "id": "monkeyisland_center",
        "name": "Monkey Island centre (marker)",
        "group": "markers",
        "variantOf": "monkeyisland",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "monkeyisland_direction",
        "name": "Monkey Island direction (marker)",
        "group": "markers",
        "variantOf": "monkeyisland",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "monkeyisland_dockgen_safeareacenter",
        "name": "Monkey Island dock area (marker)",
        "group": "markers",
        "variantOf": "monkeyisland",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "monkeyisland_portal",
        "name": "Unnatural Portal",
        "group": "landmarks",
        "variantOf": "monkeyisland",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "monkeyisland_portal_debris",
        "name": "Broken Machinery",
        "group": "landmarks",
        "variantOf": "monkeyisland",
        "always": true,
        "counts": [17, 17, 17]
    },
    { "id": "monkeypillar", "name": "Monkey Bar", "group": "mobs & dens", "always": true, "counts": [4, 4, 4] },
    {
        "id": "monkeyqueen",
        "name": "Queen of Moon Quay",
        "group": "bosses & spawners",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "monkeytail", "name": "Monkeytails", "group": "plants", "always": true, "counts": [4, 6, 9] },
    {
        "id": "moon_altar_astral_marker_1",
        "name": "Celestial Sanctum Icon spot (marker)",
        "group": "landmarks",
        "variantOf": "moon_altar_astral_marker",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "moon_altar_astral_marker_2",
        "name": "Celestial Sanctum Ward spot (marker)",
        "group": "landmarks",
        "variantOf": "moon_altar_astral_marker",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "moon_altar_rock_glass",
        "name": "Inviting Formation (Celestial Altar base)",
        "group": "landmarks",
        "variantOf": "moon_altar_rock",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "moon_altar_rock_idol",
        "name": "Inviting Formation (Celestial Altar idol)",
        "group": "landmarks",
        "variantOf": "moon_altar_rock",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "moon_altar_rock_seed",
        "name": "Inviting Formation (Celestial Altar orb)",
        "group": "landmarks",
        "variantOf": "moon_altar_rock",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "moon_fissure",
        "name": "Celestial Fissure",
        "group": "landmarks",
        "always": true,
        "counts": [37, 77, 123]
    },
    {
        "id": "moon_fissure_plugged",
        "name": "Plugged Fissure",
        "group": "landmarks",
        "always": true,
        "counts": [3, 3, 3]
    },
    {
        "id": "moon_tree",
        "name": "Lune Tree",
        "group": "trees",
        "variantOf": "moon_tree",
        "always": true,
        "counts": [81, 183, 261]
    },
    {
        "id": "moon_tree_blossom_worldgen",
        "name": "Lune Tree (blossoming)",
        "group": "trees",
        "variantOf": "moon_tree",
        "always": true,
        "counts": [11, 32, 54]
    },
    {
        "id": "moon_tree_normal",
        "name": "Lune Tree (normal)",
        "group": "trees",
        "variantOf": "moon_tree",
        "always": true,
        "counts": [9, 12, 12]
    },
    {
        "id": "moon_tree_short",
        "name": "Lune Tree (short)",
        "group": "trees",
        "variantOf": "moon_tree",
        "always": true,
        "counts": [4, 4, 4]
    },
    {
        "id": "moon_tree_tall",
        "name": "Lune Tree (tall)",
        "group": "trees",
        "variantOf": "moon_tree",
        "always": true,
        "counts": [8, 10, 10]
    },
    {
        "id": "moonbase",
        "name": "Moon Stone",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "moonglass", "name": "Moon Shard", "group": "items", "always": true, "counts": [8, 16, 29] },
    { "id": "moonglass_rock", "name": "Moon Glass", "group": "rocks", "always": true, "counts": [23, 52, 91] },
    { "id": "moonglass_wobster_den", "name": "Moon Glass Mound", "group": "mobs & dens", "counts": [0, 4, 19] },
    { "id": "moonglassaxe", "name": "Moon Glass Axe", "group": "set-piece loot", "always": true, "counts": [3, 3, 3] },
    { "id": "moonrock_pieces", "name": "Moon Rubble", "group": "rocks", "always": true, "counts": [5, 6, 6] },
    { "id": "moonrocknugget", "name": "Moon Rock", "group": "items", "counts": [0, 5, 14] },
    {
        "id": "moonspiderden",
        "name": "Shattered Spider Hole",
        "group": "mobs & dens",
        "always": true,
        "counts": [5, 5, 8]
    },
    {
        "id": "moose_nesting_ground",
        "name": "Moose/Goose nest",
        "group": "bosses & spawners",
        "always": true,
        "counts": [5, 8, 12]
    },
    { "id": "mound", "name": "Grave", "group": "structures", "always": true, "counts": [5, 7, 8] },
    {
        "id": "multiplayer_portal",
        "name": "Florid Postern (spawn portal)",
        "group": "spawn & travel",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "mushtree_tall_stump",
        "name": "Blue Mushtree (stump)",
        "group": "trees",
        "unreachable": true,
        "unique": true
    },
    { "id": "nightstick", "name": "Morning Star", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "nightsword", "name": "Dark Sword", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "oar", "name": "Oar", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "oar_driftwood", "name": "Driftwood Oar", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "oasis_cactus", "name": "Cactus (oasis)", "group": "plants", "always": true, "counts": [8, 27, 67] },
    { "id": "oasislake", "name": "Lake", "group": "landmarks", "always": true, "unique": true, "counts": [1, 1, 1] },
    {
        "id": "oceanfish_shoalspawner",
        "name": "Fish shoal",
        "group": "mobs & dens",
        "always": true,
        "counts": [3, 11, 26]
    },
    {
        "id": "oceanfishingbobber_ball",
        "name": "Wooden Ball Bobber",
        "group": "set-piece loot",
        "variantOf": "oceanfishingbobber",
        "counts": [0, 0, 2]
    },
    {
        "id": "oceanfishingbobber_crow",
        "name": "Jet Quill Float",
        "group": "set-piece loot",
        "variantOf": "oceanfishingbobber",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishingbobber_oval",
        "name": "Hardened Slip Bobber",
        "group": "set-piece loot",
        "variantOf": "oceanfishingbobber",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishingbobber_robin",
        "name": "Crimson Quill Float",
        "group": "set-piece loot",
        "variantOf": "oceanfishingbobber",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishinglure_hermit_heavy",
        "name": "Heavy Weighted Lure",
        "group": "set-piece loot",
        "variantOf": "oceanfishinglure",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishinglure_hermit_snow",
        "name": "Snow Day Lure",
        "group": "set-piece loot",
        "variantOf": "oceanfishinglure",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishinglure_spinner_blue",
        "name": "Nightflyer Spinnerbait",
        "group": "set-piece loot",
        "variantOf": "oceanfishinglure",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishinglure_spinner_green",
        "name": "Dusky Spinnerbait",
        "group": "set-piece loot",
        "variantOf": "oceanfishinglure",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishinglure_spinner_red",
        "name": "Sunrise Spinnerbait",
        "group": "set-piece loot",
        "variantOf": "oceanfishinglure",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishinglure_spoon_blue",
        "name": "Nightflyer Spoon",
        "group": "set-piece loot",
        "variantOf": "oceanfishinglure",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishinglure_spoon_green",
        "name": "Dusky Spoon",
        "group": "set-piece loot",
        "variantOf": "oceanfishinglure",
        "unique": true,
        "counts": [0, 0, 1]
    },
    {
        "id": "oceanfishinglure_spoon_red",
        "name": "Sunrise Spoon",
        "group": "set-piece loot",
        "variantOf": "oceanfishinglure",
        "counts": [0, 0, 2]
    },
    { "id": "oceanfishingrod", "name": "Sea Fishing Rod", "group": "set-piece loot", "counts": [0, 1, 4] },
    { "id": "oceantree", "name": "Knobbly Tree", "group": "trees", "always": true, "counts": [36, 54, 75] },
    { "id": "oceanvine", "name": "Mossy Vine", "group": "plants", "always": true, "counts": [33, 39, 54] },
    {
        "id": "oceanvine_cocoon",
        "name": "Sea Strider Nest",
        "group": "mobs & dens",
        "always": true,
        "counts": [3, 18, 36]
    },
    {
        "id": "oceanvine_deco",
        "name": "Mossy Vine (decoration)",
        "group": "plants",
        "always": true,
        "counts": [39, 63, 84]
    },
    {
        "id": "oceanwhirlbigportal",
        "name": "Giant Whirlpool",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "onemanband", "name": "One-man Band", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    {
        "id": "palmconetree_normal",
        "name": "Palmcone Tree (normal)",
        "group": "trees",
        "variantOf": "palmconetree",
        "always": true,
        "counts": [4, 6, 9]
    },
    {
        "id": "palmconetree_short",
        "name": "Palmcone Tree (short)",
        "group": "trees",
        "variantOf": "palmconetree",
        "counts": [0, 2, 6]
    },
    {
        "id": "palmconetree_tall",
        "name": "Palmcone Tree (tall)",
        "group": "trees",
        "variantOf": "palmconetree",
        "counts": [0, 2, 5]
    },
    { "id": "panflute", "name": "Pan Flute", "group": "set-piece loot", "always": true, "counts": [1, 1, 2] },
    { "id": "pickaxe", "name": "Pickaxe", "group": "set-piece loot", "counts": [0, 2, 6] },
    { "id": "pighead", "name": "Pig Head", "group": "structures", "always": true, "counts": [8, 12, 20] },
    { "id": "pighouse", "name": "Pig House", "group": "mobs & dens", "always": true, "counts": [15, 40, 72] },
    { "id": "pigking", "name": "Pig King", "group": "landmarks", "always": true, "unique": true, "counts": [1, 1, 1] },
    { "id": "pigman", "name": "Pig Man", "group": "mobs & dens", "counts": [0, 1, 9] },
    { "id": "pigskin", "name": "Pig Skin", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "pigtorch", "name": "Pig Torch", "group": "structures", "counts": [0, 0, 12] },
    {
        "id": "pirate_flag_pole",
        "name": "Moon Quay Pirate Banner",
        "group": "structures",
        "always": true,
        "counts": [6, 10, 16]
    },
    { "id": "pitchfork", "name": "Pitchfork", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "plantregistryhat", "name": "Gardeneer Hat", "group": "set-piece loot", "counts": [0, 0, 3] },
    { "id": "playing_card", "name": "Playing Card", "group": "set-piece loot", "always": true, "counts": [2, 3, 4] },
    {
        "id": "pond",
        "name": "Pond (frog)",
        "group": "mobs & dens",
        "variantOf": "pond",
        "always": true,
        "counts": [6, 23, 40]
    },
    {
        "id": "pond_mos",
        "name": "Pond (mosquito)",
        "group": "mobs & dens",
        "variantOf": "pond",
        "always": true,
        "counts": [5, 22, 53]
    },
    { "id": "poop", "name": "Manure", "group": "set-piece loot", "counts": [0, 0, 6] },
    { "id": "pumpkin", "name": "Pumpkin", "group": "plants", "unreachable": true, "unique": true },
    { "id": "pumpkin_lantern", "name": "Pumpkin Lantern", "group": "items", "unreachable": true, "unique": true },
    {
        "id": "pumpkincarver1",
        "name": "Pumpkin Scooper",
        "group": "set-piece loot",
        "unreachable": true,
        "unique": true
    },
    { "id": "pumpkincarver2", "name": "Pumpkin Knife", "group": "set-piece loot", "unreachable": true, "unique": true },
    { "id": "pumpkincarver3", "name": "Pumpkin Saw", "group": "set-piece loot", "unreachable": true, "unique": true },
    { "id": "rabbithole", "name": "Rabbit Hole", "group": "mobs & dens", "always": true, "counts": [34, 122, 288] },
    {
        "id": "rabbitkinghorn_container",
        "name": "Rabbit King horn container (pocket dimension, internal)",
        "group": "markers",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "raincoat", "name": "Rain Coat", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "rainhat", "name": "Rain Hat", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "red_mushroom", "name": "Red Mushroom", "group": "plants", "always": true, "counts": [25, 74, 143] },
    { "id": "redgem", "name": "Red Gem", "group": "set-piece loot", "unique": true },
    { "id": "reeds", "name": "Reeds", "group": "plants", "always": true, "counts": [33, 85, 207] },
    { "id": "reflectivevest", "name": "Summer Frest", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "researchlab", "name": "Science Machine", "group": "structures", "unique": true, "counts": [0, 0, 1] },
    { "id": "researchlab2", "name": "Alchemy Engine", "group": "structures", "unique": true },
    { "id": "researchlab3", "name": "Shadow Manipulator", "group": "structures", "unique": true },
    { "id": "resurrectionstone", "name": "Touch Stone", "group": "landmarks", "always": true, "counts": [1, 2, 2] },
    {
        "id": "rock1",
        "name": "Boulder (flint)",
        "group": "rocks",
        "variantOf": "rock",
        "always": true,
        "counts": [62, 188, 392]
    },
    {
        "id": "rock2",
        "name": "Boulder (gold)",
        "group": "rocks",
        "variantOf": "rock",
        "always": true,
        "counts": [33, 149, 329]
    },
    { "id": "rock_avocado_bush", "name": "Stone Fruit Bush", "group": "plants", "always": true, "counts": [9, 29, 55] },
    {
        "id": "rock_flintless",
        "name": "Boulder (flintless)",
        "group": "rocks",
        "variantOf": "rock",
        "always": true,
        "counts": [37, 121, 203]
    },
    { "id": "rock_ice", "name": "Mini Glacier", "group": "rocks", "counts": [0, 35, 120] },
    {
        "id": "rock_moon",
        "name": "Boulder (moon rock)",
        "group": "rocks",
        "variantOf": "rock",
        "always": true,
        "counts": [1, 8, 18]
    },
    { "id": "rocks", "name": "Rocks", "group": "items", "always": true, "counts": [51, 113, 236] },
    { "id": "rook", "name": "Clockwork Rook", "group": "clockwork", "counts": [0, 1, 3] },
    { "id": "rope", "name": "Rope", "group": "set-piece loot", "counts": [0, 0, 12] },
    { "id": "saltstack", "name": "Salt Formation", "group": "rocks", "always": true, "counts": [106, 120, 134] },
    { "id": "sanityrock", "name": "Obelisk (sane)", "group": "structures", "always": true, "counts": [4, 4, 11] },
    { "id": "sapling", "name": "Sapling", "group": "plants", "counts": [0, 761, 1255], "swapOption": "regular twigs" },
    { "id": "sapling_moon", "name": "Sapling (lunar)", "group": "plants", "always": true, "counts": [23, 54, 88] },
    {
        "id": "scorched_skeleton",
        "name": "Crispy Skeleton",
        "group": "structures",
        "always": true,
        "counts": [2, 3, 3]
    },
    { "id": "scorchedground", "name": "Scorched ground", "group": "markers", "always": true, "counts": [27, 30, 30] },
    {
        "id": "sculpture_bishop",
        "name": "Suspicious Marble (Bishop)",
        "group": "sculptures",
        "variantOf": "sculpture",
        "always": true,
        "counts": [1, 1, 6]
    },
    {
        "id": "sculpture_knight",
        "name": "Suspicious Marble (Knight)",
        "group": "sculptures",
        "variantOf": "sculpture",
        "always": true,
        "counts": [1, 1, 8]
    },
    {
        "id": "sculpture_rook",
        "name": "Suspicious Marble (Rook)",
        "group": "sculptures",
        "variantOf": "sculpture",
        "always": true,
        "counts": [1, 1, 4]
    },
    { "id": "seastack", "name": "Sea Stack", "group": "rocks", "always": true, "counts": [803, 1358, 2785] },
    {
        "id": "seastack_spawner_rough",
        "name": "Sea Stack cluster (rough)",
        "group": "ocean",
        "variantOf": "seastack_spawner",
        "always": true,
        "counts": [11, 29, 68]
    },
    {
        "id": "seastack_spawner_swell",
        "name": "Sea Stack cluster (swell)",
        "group": "ocean",
        "variantOf": "seastack_spawner",
        "always": true,
        "counts": [3, 14, 30]
    },
    { "id": "seeds", "name": "Seeds", "group": "set-piece loot", "counts": [0, 0, 4] },
    {
        "id": "shadow_container",
        "name": "Shadow container (pocket dimension, internal)",
        "group": "markers",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "shell_cluster", "name": "Shell Cluster", "group": "ocean", "always": true, "counts": [9, 9, 9] },
    { "id": "shovel", "name": "Shovel", "group": "set-piece loot", "counts": [0, 0, 3] },
    {
        "id": "singingshell_octave3",
        "name": "Baritone Shell Bell",
        "group": "items",
        "variantOf": "singingshell_octave",
        "always": true,
        "counts": [2, 2, 2]
    },
    {
        "id": "singingshell_octave4",
        "name": "Alto Shell Bell",
        "group": "items",
        "variantOf": "singingshell_octave",
        "always": true,
        "counts": [4, 4, 4]
    },
    {
        "id": "singingshell_octave5",
        "name": "Soprano Shell Bell",
        "group": "items",
        "variantOf": "singingshell_octave",
        "always": true,
        "counts": [3, 3, 3]
    },
    { "id": "skeleton", "name": "Skeleton", "group": "structures", "always": true, "counts": [6, 11, 16] },
    {
        "id": "spawnpoint_master",
        "name": "Spawn point (master)",
        "group": "spawn & travel",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "spawnpoint_multiplayer",
        "name": "Spawn point",
        "group": "spawn & travel",
        "always": true,
        "counts": [29, 51, 72]
    },
    { "id": "spear", "name": "Spear", "group": "set-piece loot", "counts": [0, 0, 4] },
    { "id": "spider_warrior", "name": "Spider Warrior", "group": "mobs & dens", "unique": true, "counts": [0, 0, 1] },
    { "id": "spiderden", "name": "Spider Den", "group": "mobs & dens", "always": true, "counts": [10, 50, 92] },
    { "id": "spoiled_fish", "name": "Spoiled Fish", "group": "set-piece loot", "counts": [0, 0, 5] },
    {
        "id": "spoiled_fish_small",
        "name": "Spoiled Fish Morsel",
        "group": "set-piece loot",
        "variantOf": "spoiled_fish",
        "counts": [0, 1, 7]
    },
    { "id": "spoiled_food", "name": "Rot", "group": "set-piece loot", "counts": [0, 3, 12] },
    {
        "id": "stagehand",
        "name": "Stagehand",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    {
        "id": "statue_marble",
        "name": "Marble Sculpture (vase)",
        "group": "statues",
        "variantOf": "statue_marble",
        "counts": [0, 0, 7]
    },
    {
        "id": "statue_marble_muse",
        "name": "Marble Sculpture (muse)",
        "group": "statues",
        "variantOf": "statue_marble",
        "counts": [0, 1, 4]
    },
    {
        "id": "statue_marble_pawn",
        "name": "Marble Sculpture (pawn)",
        "group": "statues",
        "variantOf": "statue_marble",
        "counts": [0, 1, 4]
    },
    {
        "id": "statueglommer",
        "name": "Glommer's Statue",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "statueharp", "name": "Harp Statue", "group": "statues", "counts": [0, 8, 10] },
    {
        "id": "statueharp_hedgespawner",
        "name": "Overgrown Statue",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "statuemaxwell", "name": "Maxwell Statue", "group": "statues", "counts": [0, 2, 6] },
    { "id": "stinger", "name": "Stinger", "group": "set-piece loot", "counts": [0, 0, 3] },
    {
        "id": "storage_robot",
        "name": "W.O.B.O.T.",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "strawhat", "name": "Straw Hat", "group": "set-piece loot", "counts": [0, 1, 2] },
    { "id": "sunkenchest", "name": "Sunken Chest", "group": "landmarks", "counts": [0, 1, 2] },
    { "id": "sweatervest", "name": "Dapper Vest", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "tacklecontainer", "name": "Tackle Box", "group": "structures", "counts": [0, 1, 2] },
    { "id": "tallbirdnest", "name": "Tallbird Nest", "group": "mobs & dens", "always": true, "counts": [2, 6, 30] },
    { "id": "tent", "name": "Tent", "group": "structures", "unique": true },
    { "id": "tentacle", "name": "Tentacle", "group": "mobs & dens", "always": true, "counts": [60, 214, 430] },
    {
        "id": "terrariumchest",
        "name": "Conspicuous Chest",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "tophat", "name": "Top Hat", "group": "set-piece loot", "counts": [0, 0, 2] },
    { "id": "torch", "name": "Torch", "group": "set-piece loot", "counts": [0, 0, 3] },
    { "id": "trap", "name": "Trap", "group": "set-piece loot", "counts": [0, 0, 4] },
    { "id": "trap_starfish", "name": "Anenemy", "group": "plants", "always": true, "counts": [8, 26, 55] },
    { "id": "treasurechest", "name": "Chest", "group": "structures", "counts": [0, 1, 3] },
    { "id": "trinket_1", "name": "Melty Marbles", "group": "set-piece loot", "unique": true },
    { "id": "trinket_3", "name": "Gord's Knot", "group": "set-piece loot", "unique": true },
    { "id": "trinket_8", "name": "Hardened Rubber Bung", "group": "set-piece loot", "counts": [0, 0, 2] },
    { "id": "trunkvest_summer", "name": "Breezy Vest", "group": "set-piece loot", "counts": [0, 0, 2] },
    { "id": "trunkvest_winter", "name": "Puffy Vest", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    {
        "id": "tumbleweedspawner",
        "name": "Tumbleweeds (spawner)",
        "group": "mobs & dens",
        "always": true,
        "counts": [1, 8, 21]
    },
    { "id": "twiggy_normal", "name": "Twiggy Tree (normal)", "group": "trees", "variantOf": "twiggy", "unique": true },
    { "id": "twiggy_tall", "name": "Twiggy Tree (tall)", "group": "trees", "variantOf": "twiggy", "counts": [0, 0, 3] },
    {
        "id": "twiggytree",
        "name": "Twiggy Tree",
        "group": "trees",
        "variantOf": "twiggy",
        "counts": [0, 0, 995],
        "swapOption": "twiggy trees"
    },
    {
        "id": "twigs",
        "name": "Twigs",
        "group": "items",
        "always": true,
        "counts": [11, 34, 393],
        "swapOption": "twiggy trees"
    },
    {
        "id": "wagstaff_machinery_marker",
        "name": "Wagstaff machinery spot (marker)",
        "group": "landmarks",
        "always": true,
        "unique": true,
        "counts": [1, 1, 1]
    },
    { "id": "wall_hay", "name": "Hay Wall", "group": "structures", "counts": [0, 0, 44] },
    { "id": "wall_stone", "name": "Stone Wall", "group": "structures", "unique": true },
    { "id": "wall_wood", "name": "Wood Wall", "group": "structures", "counts": [0, 0, 96] },
    {
        "id": "walrus_camp",
        "name": "MacTusk (Walrus Camp)",
        "group": "bosses & spawners",
        "always": true,
        "counts": [1, 4, 4]
    },
    { "id": "wasphive", "name": "Killer Bee Hive", "group": "mobs & dens", "always": true, "counts": [1, 14, 96] },
    { "id": "waterplant", "name": "Sea Weed", "group": "plants", "always": true, "counts": [30, 143, 380] },
    {
        "id": "waterplant_spawner_rough",
        "name": "Sea Weed cluster",
        "group": "ocean",
        "always": true,
        "counts": [3, 13, 35]
    },
    { "id": "watertree_pillar", "name": "Great Tree Trunk", "group": "trees", "always": true, "counts": [9, 9, 9] },
    { "id": "watertree_root", "name": "Great Tree Root", "group": "trees", "always": true, "counts": [6, 30, 54] },
    { "id": "winterhat", "name": "Winter Hat", "group": "set-piece loot", "unique": true, "counts": [0, 0, 1] },
    { "id": "winterometer", "name": "Thermal Measurer", "group": "structures", "unique": true },
    { "id": "wobster_den", "name": "Wobster Mound", "group": "mobs & dens", "always": true, "counts": [7, 23, 44] },
    {
        "id": "wobster_den_spawner_shore",
        "name": "Wobster Mound cluster",
        "group": "ocean",
        "always": true,
        "counts": [15, 26, 39]
    },
    {
        "id": "worm_spawner",
        "name": "Depths Worm (spawner)",
        "group": "mobs & dens",
        "unreachable": true,
        "unique": true
    },
    { "id": "wormhole", "name": "Worm Hole", "group": "spawn & travel", "always": true, "counts": [6, 8, 8] },
    { "id": "wormlight_plant", "name": "Mysterious Plant", "group": "plants", "unreachable": true, "unique": true }
];

export const LAND_TILES: LandTile[] = [
    { "name": "ROAD", "displayName": "Cobblestones", "inDefaultWorlds": true },
    { "name": "ROCKY", "displayName": "Rocky Turf", "inDefaultWorlds": true },
    { "name": "DIRT", "displayName": "Dirt", "inDefaultWorlds": true },
    { "name": "SAVANNA", "displayName": "Savanna Turf", "inDefaultWorlds": true },
    { "name": "GRASS", "displayName": "Grass Turf", "inDefaultWorlds": true },
    { "name": "FOREST", "displayName": "Forest Turf", "inDefaultWorlds": true },
    { "name": "MARSH", "displayName": "Marsh Turf", "inDefaultWorlds": true },
    { "name": "WEB", "displayName": "Web" },
    { "name": "WOODFLOOR", "displayName": "Wooden Flooring", "inDefaultWorlds": true },
    { "name": "CARPET", "displayName": "Carpeted Flooring", "inDefaultWorlds": true },
    { "name": "CHECKER", "displayName": "Checkered Flooring", "inDefaultWorlds": true },
    { "name": "CAVE", "displayName": "Guano Turf" },
    { "name": "FUNGUS", "displayName": "Fungal Turf" },
    { "name": "SINKHOLE", "displayName": "Slimy Turf" },
    { "name": "UNDERROCK", "displayName": "Cave Rock Turf" },
    { "name": "MUD", "displayName": "Mud Turf" },
    { "name": "BRICK", "displayName": "Ancient Flooring" },
    { "name": "BRICK_GLOW", "displayName": "Imitation Ancient Flooring" },
    { "name": "TILES", "displayName": "Ancient Tilework" },
    { "name": "TILES_GLOW", "displayName": "Imitation Ancient Tilework" },
    { "name": "TRIM", "displayName": "Ancient Brickwork" },
    { "name": "TRIM_GLOW", "displayName": "Imitation Ancient Brickwork" },
    { "name": "FUNGUSRED", "displayName": "Fungal Turf" },
    { "name": "FUNGUSGREEN", "displayName": "Fungal Turf" },
    { "name": "DECIDUOUS", "displayName": "Deciduous Turf", "inDefaultWorlds": true },
    { "name": "DESERT_DIRT", "displayName": "Sandy Turf", "inDefaultWorlds": true },
    { "name": "SCALE", "displayName": "Scaled Flooring" },
    { "name": "LAVAARENA_FLOOR", "displayName": "Forge Floor" },
    { "name": "LAVAARENA_TRIM", "displayName": "Forge Trim" },
    { "name": "QUAGMIRE_PEATFOREST", "displayName": "Gorge Peat Forest" },
    { "name": "QUAGMIRE_PARKFIELD", "displayName": "Gorge Park Grass" },
    { "name": "QUAGMIRE_PARKSTONE", "displayName": "Gorge Park Path" },
    { "name": "QUAGMIRE_GATEWAY", "displayName": "Gorge Gateway" },
    { "name": "QUAGMIRE_SOIL", "displayName": "Gorge Soil" },
    { "name": "QUAGMIRE_CITYSTONE", "displayName": "Gorge Citystone" },
    { "name": "PEBBLEBEACH", "displayName": "Rocky Beach Turf", "inDefaultWorlds": true },
    { "name": "METEOR", "displayName": "Moon Crater Turf", "inDefaultWorlds": true },
    { "name": "SHELLBEACH", "displayName": "Shell Beach Turf", "inDefaultWorlds": true },
    { "name": "ARCHIVE", "displayName": "Ancient Stonework" },
    { "name": "FUNGUSMOON", "displayName": "Mutated Fungal Turf" },
    { "name": "FARMING_SOIL", "displayName": "Farm soil" },
    { "name": "FUNGUSMOON_NOISE", "displayName": "Fungusmoon Noise" },
    { "name": "METEORMINE_NOISE", "displayName": "Meteormine Noise" },
    { "name": "METEORCOAST_NOISE", "displayName": "Meteorcoast Noise" },
    { "name": "DIRT_NOISE", "displayName": "Dirt Noise" },
    { "name": "ABYSS_NOISE", "displayName": "Abyss Noise" },
    { "name": "GROUND_NOISE", "displayName": "Ground Noise" },
    { "name": "CAVE_NOISE", "displayName": "Cave Noise" },
    { "name": "FUNGUS_NOISE", "displayName": "Fungus Noise" },
    { "name": "COTL_BRICK", "displayName": "Brick Flooring" },
    { "name": "MONKEY_GROUND", "displayName": "Moon Quay Beach Turf", "inDefaultWorlds": true },
    { "name": "LUNAR_MARSH", "displayName": "Lunar Marsh" },
    { "name": "SHADOW_MARSH", "displayName": "Shadow Marsh" },
    { "name": "VENT", "displayName": "Cave Fumarole Turf" },
    { "name": "VAULT", "displayName": "Vault" },
    { "name": "VAULT_CLEAN", "displayName": "Ancient Sanctum Stonework" },
    { "name": "MONKEY_DOCK", "displayName": "Monkey Island dock", "inDefaultWorlds": true },
    { "name": "OCEAN_ICE", "displayName": "Ocean (ice)" },
    { "name": "CHARLIE_VINE", "displayName": "Charlie Vine" },
    { "name": "ROPE_BRIDGE", "displayName": "Rope Bridge" },
    { "name": "WAGSTAFF_FLOOR", "displayName": "Wagstaff Floor" },
    { "name": "COTL_GOLD", "displayName": "Gold Flooring" },
    { "name": "MOSAIC_GREY", "displayName": "Grey Mosaic Flooring", "inDefaultWorlds": true },
    { "name": "MOSAIC_RED", "displayName": "Red Mosaic Flooring" },
    { "name": "MOSAIC_BLUE", "displayName": "Blue Mosaic Flooring" },
    { "name": "CARPET2", "displayName": "Lush Carpet", "inDefaultWorlds": true },
    { "name": "BEARD_RUG", "displayName": "Beard Hair Rug" },
    { "name": "RIFT_MOON", "displayName": "Lunar Rift" },
    { "name": "VENT_NOISE", "displayName": "Vent Noise" }
];

export const NON_LAND_TILE_NAMES: string[] = ["IMPASSABLE", "UNDERGROUND", "WALL_ROCKY", "WALL_DIRT", "WALL_MARSH", "WALL_CAVE", "WALL_FUNGUS", "WALL_SINKHOLE", "WALL_MUD", "WALL_TOP", "WALL_WOOD", "WALL_HUNESTONE", "WALL_HUNESTONE_GLOW", "WALL_STONEEYE", "WALL_STONEEYE_GLOW", "FAKE_GROUND", "OCEAN_COASTAL", "OCEAN_COASTAL_SHORE", "OCEAN_SWELL", "OCEAN_ROUGH", "OCEAN_BRINEPOOL", "OCEAN_BRINEPOOL_SHORE", "OCEAN_HAZARDOUS", "OCEAN_WATERLOG", "OCEAN_END", "INVALID"];

export const TILES: Readonly<Record<string, MapTile>> = {
    "IMPASSABLE": { "displayName": "Impassable", "kind": "impassable", "color": [172, 172, 172] },
    "ROAD": { "displayName": "Cobblestones", "kind": "land", "color": [210, 210, 210] },
    "ROCKY": { "displayName": "Rocky Turf", "kind": "land", "color": [192, 192, 186] },
    "DIRT": { "displayName": "Dirt", "kind": "land", "color": [249, 249, 249] },
    "SAVANNA": { "displayName": "Savanna Turf", "kind": "land", "color": [221, 198, 118] },
    "GRASS": { "displayName": "Grass Turf", "kind": "land", "color": [199, 230, 145] },
    "FOREST": { "displayName": "Forest Turf", "kind": "land", "color": [115, 150, 120] },
    "MARSH": { "displayName": "Marsh Turf", "kind": "land", "color": [124, 114, 132] },
    "WEB": { "displayName": "Web", "kind": "land", "color": [172, 172, 172] },
    "WOODFLOOR": { "displayName": "Wooden Flooring", "kind": "land", "color": [169, 159, 130] },
    "CARPET": { "displayName": "Carpeted Flooring", "kind": "land", "color": [174, 131, 123] },
    "CHECKER": { "displayName": "Checkered Flooring", "kind": "land", "color": [203, 185, 177] },
    "CAVE": { "displayName": "Guano Turf", "kind": "land", "color": [156, 165, 184] },
    "FUNGUS": { "displayName": "Fungal Turf", "kind": "land", "color": [68, 104, 174] },
    "SINKHOLE": { "displayName": "Slimy Turf", "kind": "land", "color": [130, 154, 97] },
    "UNDERROCK": { "displayName": "Cave Rock Turf", "kind": "land", "color": [100, 100, 110] },
    "MUD": { "displayName": "Mud Turf", "kind": "land", "color": [132, 104, 71] },
    "BRICK": { "displayName": "Ancient Flooring", "kind": "land", "color": [107, 129, 142] },
    "BRICK_GLOW": { "displayName": "Imitation Ancient Flooring", "kind": "land", "color": [107, 129, 142] },
    "TILES": { "displayName": "Ancient Tilework", "kind": "land", "color": [93, 67, 113] },
    "TILES_GLOW": { "displayName": "Imitation Ancient Tilework", "kind": "land", "color": [93, 67, 113] },
    "TRIM": { "displayName": "Ancient Brickwork", "kind": "land", "color": [49, 50, 65] },
    "TRIM_GLOW": { "displayName": "Imitation Ancient Brickwork", "kind": "land", "color": [93, 67, 113] },
    "FUNGUSRED": { "displayName": "Fungal Turf", "kind": "land", "color": [143, 109, 119] },
    "FUNGUSGREEN": { "displayName": "Fungal Turf", "kind": "land", "color": [93, 107, 95] },
    "DECIDUOUS": { "displayName": "Deciduous Turf", "kind": "land", "color": [162, 136, 135] },
    "DESERT_DIRT": { "displayName": "Sandy Turf", "kind": "land", "color": [227, 221, 185] },
    "SCALE": { "displayName": "Scaled Flooring", "kind": "land", "color": [76, 72, 56] },
    "LAVAARENA_FLOOR": { "displayName": "Forge Floor", "kind": "land", "color": [110, 28, 0] },
    "LAVAARENA_TRIM": { "displayName": "Forge Trim", "kind": "land", "color": [110, 28, 0] },
    "QUAGMIRE_PEATFOREST": { "displayName": "Gorge Peat Forest", "kind": "land", "color": [158, 157, 172] },
    "QUAGMIRE_PARKFIELD": { "displayName": "Gorge Park Grass", "kind": "land", "color": [162, 136, 135] },
    "QUAGMIRE_PARKSTONE": { "displayName": "Gorge Park Path", "kind": "land", "color": [232, 220, 232] },
    "QUAGMIRE_GATEWAY": { "displayName": "Gorge Gateway", "kind": "land", "color": [130, 154, 97] },
    "QUAGMIRE_SOIL": { "displayName": "Gorge Soil", "kind": "land", "color": [70, 63, 51] },
    "QUAGMIRE_CITYSTONE": { "displayName": "Gorge Citystone", "kind": "land", "color": [217, 218, 217] },
    "PEBBLEBEACH": { "displayName": "Rocky Beach Turf", "kind": "land", "color": [187, 205, 201] },
    "METEOR": { "displayName": "Moon Crater Turf", "kind": "land", "color": [127, 193, 206] },
    "SHELLBEACH": { "displayName": "Shell Beach Turf", "kind": "land", "color": [151, 163, 229] },
    "ARCHIVE": { "displayName": "Ancient Stonework", "kind": "land", "color": [155, 128, 106] },
    "FUNGUSMOON": { "displayName": "Mutated Fungal Turf", "kind": "land", "color": [53, 94, 100] },
    "FARMING_SOIL": { "displayName": "Farm soil", "kind": "land", "color": [70, 63, 51] },
    "FUNGUSMOON_NOISE": { "displayName": "Fungusmoon Noise", "kind": "land", "color": [172, 172, 172] },
    "METEORMINE_NOISE": { "displayName": "Meteormine Noise", "kind": "land", "color": [172, 172, 172] },
    "METEORCOAST_NOISE": { "displayName": "Meteorcoast Noise", "kind": "land", "color": [172, 172, 172] },
    "DIRT_NOISE": { "displayName": "Dirt Noise", "kind": "land", "color": [172, 172, 172] },
    "ABYSS_NOISE": { "displayName": "Abyss Noise", "kind": "land", "color": [172, 172, 172] },
    "GROUND_NOISE": { "displayName": "Ground Noise", "kind": "land", "color": [172, 172, 172] },
    "CAVE_NOISE": { "displayName": "Cave Noise", "kind": "land", "color": [172, 172, 172] },
    "FUNGUS_NOISE": { "displayName": "Fungus Noise", "kind": "land", "color": [172, 172, 172] },
    "UNDERGROUND": { "displayName": "Underground", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_ROCKY": { "displayName": "Wall Rocky", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_DIRT": { "displayName": "Wall Dirt", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_MARSH": { "displayName": "Wall Marsh", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_CAVE": { "displayName": "Wall Cave", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_FUNGUS": { "displayName": "Wall Fungus", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_SINKHOLE": { "displayName": "Wall Sinkhole", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_MUD": { "displayName": "Wall Mud", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_TOP": { "displayName": "Wall Top", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_WOOD": { "displayName": "Wall Wood", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_HUNESTONE": { "displayName": "Wall Hunestone", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_HUNESTONE_GLOW": { "displayName": "Wall Hunestone Glow", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_STONEEYE": { "displayName": "Wall Stoneeye", "kind": "impassable", "color": [172, 172, 172] },
    "WALL_STONEEYE_GLOW": { "displayName": "Wall Stoneeye Glow", "kind": "impassable", "color": [172, 172, 172] },
    "FAKE_GROUND": { "displayName": "Fake Ground", "kind": "impassable", "color": [172, 172, 172] },
    "OCEAN_COASTAL": { "displayName": "Ocean (coastal)", "kind": "ocean", "color": [8, 27, 22] },
    "OCEAN_COASTAL_SHORE": { "displayName": "Ocean (shore)", "kind": "ocean", "color": [99, 167, 170] },
    "OCEAN_SWELL": { "displayName": "Ocean (swell)", "kind": "ocean", "color": [5, 18, 22] },
    "OCEAN_ROUGH": { "displayName": "Ocean (rough)", "kind": "ocean", "color": [7, 11, 14] },
    "OCEAN_BRINEPOOL": { "displayName": "Ocean (brine pool)", "kind": "ocean", "color": [14, 46, 33] },
    "OCEAN_BRINEPOOL_SHORE": { "displayName": "Ocean (brine pool shore)", "kind": "ocean", "color": [76, 175, 182] },
    "OCEAN_HAZARDOUS": { "displayName": "Ocean (hazardous)", "kind": "ocean", "color": [3, 4, 5] },
    "OCEAN_WATERLOG": { "displayName": "Ocean (waterlogged)", "kind": "ocean", "color": [14, 46, 33] },
    "OCEAN_END": { "displayName": "Ocean End", "kind": "ocean", "color": [172, 172, 172] },
    "COTL_BRICK": { "displayName": "Brick Flooring", "kind": "land", "color": [127, 120, 104] },
    "MONKEY_GROUND": { "displayName": "Moon Quay Beach Turf", "kind": "land", "color": [187, 205, 201] },
    "LUNAR_MARSH": { "displayName": "Lunar Marsh", "kind": "land", "color": [124, 114, 132] },
    "SHADOW_MARSH": { "displayName": "Shadow Marsh", "kind": "land", "color": [124, 114, 132] },
    "VENT": { "displayName": "Cave Fumarole Turf", "kind": "land", "color": [92, 91, 90] },
    "VAULT": { "displayName": "Vault", "kind": "land", "color": [138, 120, 91] },
    "VAULT_CLEAN": { "displayName": "Ancient Sanctum Stonework", "kind": "land", "color": [138, 120, 91] },
    "MONKEY_DOCK": { "displayName": "Monkey Island dock", "kind": "land", "color": [100, 81, 49] },
    "OCEAN_ICE": { "displayName": "Ocean (ice)", "kind": "land", "color": [49, 78, 83] },
    "CHARLIE_VINE": { "displayName": "Charlie Vine", "kind": "land", "color": [221, 198, 118] },
    "ROPE_BRIDGE": { "displayName": "Rope Bridge", "kind": "land", "color": [169, 159, 130] },
    "WAGSTAFF_FLOOR": { "displayName": "Wagstaff Floor", "kind": "land", "color": [169, 159, 130] },
    "COTL_GOLD": { "displayName": "Gold Flooring", "kind": "land", "color": [164, 140, 62] },
    "MOSAIC_GREY": { "displayName": "Grey Mosaic Flooring", "kind": "land", "color": [54, 48, 58] },
    "MOSAIC_RED": { "displayName": "Red Mosaic Flooring", "kind": "land", "color": [100, 37, 69] },
    "MOSAIC_BLUE": { "displayName": "Blue Mosaic Flooring", "kind": "land", "color": [55, 44, 69] },
    "CARPET2": { "displayName": "Lush Carpet", "kind": "land", "color": [37, 11, 39] },
    "BEARD_RUG": { "displayName": "Beard Hair Rug", "kind": "land", "color": [0, 0, 0] },
    "RIFT_MOON": { "displayName": "Lunar Rift", "kind": "land", "color": [152, 181, 181] },
    "VENT_NOISE": { "displayName": "Vent Noise", "kind": "land", "color": [172, 172, 172] },
    "INVALID": { "displayName": "Invalid", "kind": "invalid", "color": [172, 172, 172] }
};

export const NAMED_ANCHORS: NamedAnchor[] = [
    { "id": "multiplayer_portal", "label": "Spawn (Florid Postern)" },
    { "id": "pigking", "label": "Pig King" },
    { "id": "moonbase", "label": "Moon Stone" },
    { "id": "dragonfly_spawner", "label": "Dragonfly" },
    { "id": "beequeenhive", "label": "Bee Queen (Gigantic Beehive)" },
    { "id": "antlion_spawner", "label": "Antlion" },
    { "id": "crabking_spawner", "label": "Crab King" },
    { "id": "hermithouse_construction1", "label": "Crabby Hermit (Pearl's house)" },
    { "id": "monkeyqueen", "label": "Queen of Moon Quay" },
    { "id": "wormhole", "label": "Worm Hole" }
];

export const PREFAB_BY_ID: ReadonlyMap<string, WorldPrefab> = new Map(PREFABS.map((prefab) => [prefab.id, prefab]));

export const PREFAB_GROUPS: PrefabGroup[] = PREFAB_GROUP_IDS.map((id) => ({
    id,
    name: id.charAt(0).toUpperCase() + id.slice(1),
    prefabs: PREFABS.filter((prefab) => prefab.group === id).map((prefab) => prefab.id)
}));

export const PREFAB_VARIANTS: ReadonlyMap<string, string[]> = PREFABS.reduce((variants, prefab) => {
    if (prefab.variantOf) variants.set(prefab.variantOf, [...(variants.get(prefab.variantOf) ?? []), prefab.id]);
    return variants;
}, new Map<string, string[]>());
